ALTER TABLE professores
ADD COLUMN logradouro VARCHAR(100) NOT NULL,
ADD COLUMN bairro VARCHAR(50) NOT NULL,
ADD COLUMN cep VARCHAR(10) NOT NULL,
ADD COLUMN uf VARCHAR(2) NOT NULL,
ADD COLUMN cidade VARCHAR(50) NOT NULL,
ADD COLUMN numero VARCHAR(10), -- Considerando número como inteiro
ADD COLUMN complemento VARCHAR(100);